In [105]:
import numpy as np 
import pandas as pd

In [106]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\naikv\anaconda3\lib\site-packages (26.7.0)

In [107]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345",
    database="ecommerce_analytics"
)

print("MySQL connected successfully!")

MySQL connected successfully!

In [108]:
print(conn.is_connected())

True

In [109]:
cursor = conn.cursor()

query = 'select * from customers limit 10'

cursor.execute(query)

In [110]:
result = cursor.fetchall()

In [111]:
print(result)

[('C0001', 'Customer_0001', 'Male', 34, 'Mumbai', 'West', datetime.date(2023, 1, 21)), ('C0002', 'Customer_0002', 'Female', 26, 'Hyderabad', 'South', datetime.date(2025, 9, 10)), ('C0003', 'Customer_0003', 'Male', 50, 'Pune', 'West', datetime.date(2023, 11, 1)), ('C0004', 'Customer_0004', 'Male', 37, 'Bengaluru', 'South', datetime.date(2024, 1, 6)), ('C0005', 'Customer_0005', 'Male', 30, 'Chennai', 'South', datetime.date(2025, 5, 2)), ('C0006', 'Customer_0006', 'Female', 45, 'Jaipur', 'North', datetime.date(2024, 1, 19)), ('C0007', 'Customer_0007', 'Male', 46, 'Lucknow', 'North', datetime.date(2024, 3, 20)), ('C0008', 'Customer_0008', 'Male', 30, 'Bengaluru', 'South', datetime.date(2024, 2, 29)), ('C0009', 'Customer_0009', 'Male', 52, 'Hyderabad', 'South', datetime.date(2023, 6, 10)), ('C0010', 'Customer_0010', 'Female', 23, 'Ahmedabad', 'West', datetime.date(2024, 9, 20))]

In [112]:
result [ :5]

[('C0001',
  'Customer_0001',
  'Male',
  34,
  'Mumbai',
  'West',
  datetime.date(2023, 1, 21)),
 ('C0002',
  'Customer_0002',
  'Female',
  26,
  'Hyderabad',
  'South',
  datetime.date(2025, 9, 10)),
 ('C0003',
  'Customer_0003',
  'Male',
  50,
  'Pune',
  'West',
  datetime.date(2023, 11, 1)),
 ('C0004',
  'Customer_0004',
  'Male',
  37,
  'Bengaluru',
  'South',
  datetime.date(2024, 1, 6)),
 ('C0005',
  'Customer_0005',
  'Male',
  30,
  'Chennai',
  'South',
  datetime.date(2025, 5, 2))]

In [113]:
customers = pd.read_sql('select * from customers  ', conn)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\3622898415.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql('select * from customers  ', conn)

In [114]:
customers.head()

  customer_Id  customer_name  Gender  Age       City Region  SignupDate
0       C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1       C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2       C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3       C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4       C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [115]:
customers.shape

(1000, 7)

In [116]:
customers.columns

Index(['customer_Id', 'customer_name', 'Gender', 'Age', 'City', 'Region',
       'SignupDate'],
      dtype='object')

In [117]:
customers.dtypes

customer_Id      object
customer_name    object
Gender           object
Age               int64
City             object
Region           object
SignupDate       object
dtype: object

In [118]:
Orders = pd.read_sql('select * from Orders', conn)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\413930625.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Orders = pd.read_sql('select * from Orders', conn)

In [119]:
Orders. head()

  Order_ID   OrderDate customer_Id Paymentmethod orderStatus
0   O00001  2026-01-19       C0484           UPI   Delivered
1   O00002  2026-02-14       C0450   Credit Card   Delivered
2   O00003  2025-11-21       C0523   Credit Card   Delivered
3   O00004  2025-05-08       C0871           UPI   Delivered
4   O00005  2025-05-04       C0354   Net Banking   Delivered

In [120]:
Orders. shape

(5000, 5)

In [121]:
Orders. columns

Index(['Order_ID', 'OrderDate', 'customer_Id', 'Paymentmethod', 'orderStatus'], dtype='object')

In [122]:
Orderdetails = pd.read_sql('select * from Orderdetails', conn)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\3255218468.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Orderdetails = pd.read_sql('select * from Orderdetails', conn)

In [123]:
Orderdetails. head()

,OrderDetails_ID,Order_ID,product_ID,Quantity,Unitprice,Discountprice,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [124]:
Orderdetails. shape

(12558, 8)

In [125]:
Orderdetails. dtypes

OrderDetails_ID     object
Order_ID            object
product_ID          object
Quantity             int64
Unitprice          float64
Discountprice      float64
SalesAmount        float64
Profit             float64
dtype: object

In [126]:
products = pd.read_sql('select * from  products', conn)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\1386897054.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql('select * from  products', conn)

In [127]:
products . head()

  Product_Id         Product_name     Category  Costprice  Sellingprice
0      P0001  Wireless Headphones  Electronics     4840.0        8847.0
1      P0002  Wireless Headphones  Electronics     4745.0        8892.0
2      P0003  Wireless Headphones  Electronics      262.0         319.0
3      P0004          Smart Watch  Electronics     2528.0        3517.0
4      P0005          Smart Watch  Electronics      289.0         526.0

In [128]:
products .shape

(82, 5)

In [129]:
products. dtypes

Product_Id       object
Product_name     object
Category         object
Costprice       float64
Sellingprice    float64
dtype: object

In [130]:
returns = pd.read_sql('select * from  Returns', conn)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\3888428537.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  returns = pd.read_sql('select * from  Returns', conn)

In [131]:
returns . head()

  Return_ID Order_ID  ReturnDate   ReturnReason
0    R00001   O00016  1970-01-01        Damaged
1    R00002   O00078  1970-01-01  Wrong Product
2    R00003   O00088  1970-01-01     Size Issue
3    R00004   O00124  1970-01-01     Size Issue
4    R00005   O00125  1970-01-01  Late Delivery

In [132]:
returns .dtypes

Return_ID       object
Order_ID        object
ReturnDate      object
ReturnReason    object
dtype: object

In [133]:
print("customers:", customers.shape)
print("products:", products.shape)
print("Orders:", Orders.shape)
print("orderdetails:", Orderdetails.shape)
print("returns:" ,returns.shape)

customers: (1000, 7)
products: (82, 5)
Orders: (5000, 5)
orderdetails: (12558, 8)
returns: (257, 4)

In [134]:
query = """
SELECT 
    SUM(od.salesAmount) AS totalRevenue,
    SUM(od.Profit) AS totalprofit
FROM Orders o
JOIN OrderDetails od
    ON o.Order_ID = od.Order_ID
WHERE o.OrderStatus = 'Delivered';
"""
revenue_summary = pd.read_sql(
    query,
    conn
)

C:\Users\naikv\AppData\Local\Temp\ipykernel_7840\1032105817.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  revenue_summary = pd.read_sql(

In [135]:
print(revenue_summary)

   totalRevenue  totalprofit
0  1.533119e+08  52519937.55

In [136]:
cursor.close()
conn.close()

In [137]:
# data frame check 
customers. shape

(1000, 7)

In [138]:
products. shape

(82, 5)

In [139]:
Orders. shape

(5000, 5)

In [140]:
Orderdetails. shape

(12558, 8)

In [141]:
returns.shape

(257, 4)

In [142]:
# first 5 record check 
customers.head(5)

  customer_Id  customer_name  Gender  Age       City Region  SignupDate
0       C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1       C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2       C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3       C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4       C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [143]:
products. head()

  Product_Id         Product_name     Category  Costprice  Sellingprice
0      P0001  Wireless Headphones  Electronics     4840.0        8847.0
1      P0002  Wireless Headphones  Electronics     4745.0        8892.0
2      P0003  Wireless Headphones  Electronics      262.0         319.0
3      P0004          Smart Watch  Electronics     2528.0        3517.0
4      P0005          Smart Watch  Electronics      289.0         526.0

In [144]:
Orders. head()

  Order_ID   OrderDate customer_Id Paymentmethod orderStatus
0   O00001  2026-01-19       C0484           UPI   Delivered
1   O00002  2026-02-14       C0450   Credit Card   Delivered
2   O00003  2025-11-21       C0523   Credit Card   Delivered
3   O00004  2025-05-08       C0871           UPI   Delivered
4   O00005  2025-05-04       C0354   Net Banking   Delivered

In [145]:
Orderdetails. head()

,OrderDetails_ID,Order_ID,product_ID,Quantity,Unitprice,Discountprice,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [146]:

returns.head()

  Return_ID Order_ID  ReturnDate   ReturnReason
0    R00001   O00016  1970-01-01        Damaged
1    R00002   O00078  1970-01-01  Wrong Product
2    R00003   O00088  1970-01-01     Size Issue
3    R00004   O00124  1970-01-01     Size Issue
4    R00005   O00125  1970-01-01  Late Delivery

In [147]:
 Orders.dtypes

Order_ID         object
OrderDate        object
customer_Id      object
Paymentmethod    object
orderStatus      object
dtype: object

In [148]:
Orders['OrderDate'] = pd.to_datetime(Orders['OrderDate'])

In [149]:
Orders.dtypes

Order_ID                 object
OrderDate        datetime64[ns]
customer_Id              object
Paymentmethod            object
orderStatus              object
dtype: object

In [150]:
customers['SignupDate'] = pd.to_datetime(customers['SignupDate'])

In [151]:
customers.dtypes

customer_Id              object
customer_name            object
Gender                   object
Age                       int64
City                     object
Region                   object
SignupDate       datetime64[ns]
dtype: object

In [152]:
# misssing value check 
customers.isnull().sum()

customer_Id      0
customer_name    0
Gender           0
Age              0
City             0
Region           0
SignupDate       0
dtype: int64

In [153]:
Orders.isnull().sum()

Order_ID         0
OrderDate        0
customer_Id      0
Paymentmethod    0
orderStatus      0
dtype: int64

In [154]:
Orderdetails.isnull().sum()

OrderDetails_ID    0
Order_ID           0
product_ID         0
Quantity           0
Unitprice          0
Discountprice      0
SalesAmount        0
Profit             0
dtype: int64

In [155]:
products.isnull().sum()

Product_Id      0
Product_name    0
Category        0
Costprice       0
Sellingprice    0
dtype: int64

In [156]:
returns.isnull().sum()

Return_ID       0
Order_ID        0
ReturnDate      0
ReturnReason    0
dtype: int64

In [157]:
# duplicate record check
print("Customers Duplicates:", customers.duplicated().sum())
print("Orders Duplicates:", Orders.duplicated().sum())
print("OrderDetails Duplicates:", Orderdetails.duplicated().sum())
print("Products Duplicates:", products.duplicated().sum())

Customers Duplicates: 0
Orders Duplicates: 0
OrderDetails Duplicates: 0
Products Duplicates: 0

In [158]:
# numeric data check 
Orderdetails. describe()

           Quantity     Unitprice  Discountprice   SalesAmount        Profit
count  12558.000000  12558.000000   12558.000000  12558.000000  12558.000000
mean       2.501752   6272.299570      10.742156  14010.138708   4804.382457
std        1.119501   3461.536155       7.112802  10628.052040   4894.725391
min        1.000000    319.000000       0.000000    239.250000  -2048.000000
25%        2.000000   3416.000000       5.000000   5949.000000   1342.400000
50%        2.000000   6288.000000      10.000000  11210.400000   3215.600000
75%        4.000000   8847.000000      15.000000  20044.800000   6608.400000
max        4.000000  14270.000000      25.000000  57080.000000  30860.000000

In [159]:
# imposible value check 
Orderdetails [ Orderdetails["Quantity"]<= 0]

Empty DataFrame
Columns: [OrderDetails_ID, Order_ID, product_ID, Quantity, Unitprice, Discountprice, SalesAmount, Profit]
Index: []

In [160]:
Orderdetails[
    (Orderdetails["Discountprice"] < 0) |
    (Orderdetails["Discountprice"] > 100)
]

Empty DataFrame
Columns: [OrderDetails_ID, Order_ID, product_ID, Quantity, Unitprice, Discountprice, SalesAmount, Profit]
Index: []

In [161]:
Orderdetails[Orderdetails["SalesAmount"] < 0]

Empty DataFrame
Columns: [OrderDetails_ID, Order_ID, product_ID, Quantity, Unitprice, Discountprice, SalesAmount, Profit]
Index: []

In [162]:
# customer age valiation 
customers[
    (customers['Age'] < 18) |
    (customers['Age'] > 100)
]

Empty DataFrame
Columns: [customer_Id, customer_name, Gender, Age, City, Region, SignupDate]
Index: []

In [163]:
 
# create analytical dataset

df = Orders.merge(
    customers,
    on="customer_Id",
    how="left"
)

In [164]:
# 2. Add OrderDetails
df = df.merge(
    Orderdetails,
    on="Order_ID",
    how="inner"
)

In [165]:
df

,Order_ID,OrderDate,customer_Id,Paymentmethod,orderStatus,customer_name,Gender,Age,City,Region,SignupDate,OrderDetails_ID,product_ID,Quantity,Unitprice,Discountprice,SalesAmount,Profit
0,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,2024-02-03,OD000001,P0014,4,10018.0,15.0,34061.20,12649.20
1,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,2024-02-03,OD000002,P0063,3,5568.0,5.0,15868.80,6532.80
2,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,2023-05-19,OD000003,P0030,1,10331.0,5.0,9814.45,3909.45
3,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,2023-05-19,OD000004,P0027,4,4363.0,10.0,15706.80,2006.80
4,O00003,2025-11-21,C0523,Credit Card,Delivered,Customer_0523,Female,60,Delhi,North,2025-03-04,OD000005,P0040,2,6601.0,5.0,12541.90,4543.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12553,O04999,2026-03-20,C0371,Credit Card,Delivered,Customer_0371,Female,46,Lucknow,North,2024-01-10,OD012554,P0008,1,9277.0,5.0,8813.15,2402.15
12554,O04999,2026-03-20,C0371,Credit Card,Delivered,Customer_0371,Female,46,Lucknow,North,2024-01-10,OD012555,P0004,2,3517.0,15.0,5978.90,922.90
12555,O05000,2025-12-16,C0777,COD,Delivered,Customer_0777,Male,56,Chennai,South,2024-07-13,OD012556,P0009,4,4834.0,15.0,16435.60,3419.60
12556,O05000,2025-12-16,C0777,COD,Delivered,Customer_0777,Male,56,Chennai,South,2024-07-13,OD012557,P0050,3,791.0,20.0,1898.40,599.40
12557,O05000,2025-12-16,C0777,COD,Delivered,Customer_0777,Male,56,Chennai,South,2024-07-13,OD012558,P0065,2,1750.0,0.0,3500.00,1072.00

In [178]:
products

   Product_Id         Product_name     Category  Costprice  Sellingprice
0       P0001  Wireless Headphones  Electronics     4840.0        8847.0
1       P0002  Wireless Headphones  Electronics     4745.0        8892.0
2       P0003  Wireless Headphones  Electronics      262.0         319.0
3       P0004          Smart Watch  Electronics     2528.0        3517.0
4       P0005          Smart Watch  Electronics      289.0         526.0
..        ...                  ...          ...        ...           ...
77      P0078           Excel Book        Books     1723.0        2727.0
78      P0079        Power BI Book        Books     5433.0       11587.0
79      P0080        Power BI Book        Books     6882.0       13672.0
80      P0081      Statistics Book        Books     2584.0        4694.0
81      P0082      Statistics Book        Books     1164.0        2255.0

[82 rows x 5 columns]

In [186]:
print("df columns:")
print(df.columns.tolist())

print("\nproducts columns:")
print(products.columns.tolist())

df columns:
['Order_ID', 'OrderDate', 'customer_Id', 'Paymentmethod', 'orderStatus', 'customer_name', 'Gender', 'Age', 'City', 'Region', 'SignupDate', 'OrderDetails_ID', 'product_ID', 'Quantity', 'Unitprice', 'Discountprice', 'SalesAmount', 'Profit']

products columns:
['Product_Id', 'Product_name', 'Category', 'Costprice', 'Sellingprice']

In [187]:
df = df.merge(
    products,
    left_on="product_ID",
    right_on="Product_Id",
    how="left"
)

In [188]:
df. shape

(12558, 23)

In [189]:
df.duplicated().sum()

np.int64(0)

In [190]:
df.drop(columns=["Product_Id"], inplace=True)

In [191]:
df. shape

(12558, 22)

In [192]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month
df["MonthName"] = df["OrderDate"].dt.month_name()
df["Quarter"] = df["OrderDate"].dt.quarter
df["Day"] = df["OrderDate"].dt.day
df["OrderDayName"] = df["OrderDate"].dt.day_name()
df["YearMonth"] = df["OrderDate"].dt.to_period("M").astype(str)

In [194]:
# profit margin
df["Profit_Margin"] = (df["Profit"] / df["SalesAmount"]) * 100

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12558 entries, 0 to 12557
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         12558 non-null  object
 1   OrderDate        12558 non-null  datetime64[ns]
 2   customer_Id      12558 non-null  object
 3   Paymentmethod    12558 non-null  object
 4   orderStatus      12558 non-null  object
 5   customer_name    12558 non-null  object
 6   Gender           12558 non-null  object
 7   Age              12558 non-null  int64
 8   City             12558 non-null  object
 9   Region           12558 non-null  object
 10  SignupDate       12558 non-null  datetime64[ns]
 11  OrderDetails_ID  12558 non-null  object
 12  product_ID       12558 non-null  object
 13  Quantity         12558 non-null  int64
 14  Unitprice        12558 non-null  float64
 15  Discountprice    12558 non-null  float64
 16  SalesAmount      12558 non-null  float64
 17  Profit           12558 non-null  float64
 18  Product_name     12558 non-null  object
 19  Category         12558 non-null  object
 20  Costprice        12558 non-null  float64
 21  Sellingprice     12558 non-null  float64
 22  Year             12558 non-null  int32
 23  Month            12558 non-null  int32
 24  MonthName        12558 non-null  object
 25  Quarter          12558 non-null  int32
 26  Day              12558 non-null  int32
 27  OrderDayName     12558 non-null  object
 28  YearMonth        12558 non-null  object
 29  Profit_Margin    12558 non-null  float64
dtypes: datetime64[ns](2), float64(7), int32(4), int64(2), object(15)
memory usage: 2.7+ MB

In [198]:
df.isnull().sum()

Order_ID           0
OrderDate          0
customer_Id        0
Paymentmethod      0
orderStatus        0
customer_name      0
Gender             0
Age                0
City               0
Region             0
SignupDate         0
OrderDetails_ID    0
product_ID         0
Quantity           0
Unitprice          0
Discountprice      0
SalesAmount        0
Profit             0
Product_name       0
Category           0
Costprice          0
Sellingprice       0
Year               0
Month              0
MonthName          0
Quarter            0
Day                0
OrderDayName       0
YearMonth          0
Profit_Margin      0
dtype: int64

In [199]:
df.duplicated().sum()

np.int64(0)

In [201]:
df.to_csv(
    "ecommerce_clean_data.csv",
    index=False
)